name: geo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - geopandas=0.14.3
  - pandas=2.3.2
  - numpy=1.26.4
  - shapely=2.1.2
  - matplotlib=3.10.6
  - fiona=1.9.6
  - pyproj=3.7.2
  - osmnx
  - folium
  - requests
  - statsmodels
  - scipy
  - jupyter
  - ipykernel
  - pip:
    - overturemaps
    - earthengine-api
    - geemap
    - pystac-client
    - planetary-computer
